name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: windows-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
     # sets up .NET Core SDK 5.0.403
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    - name: Install dependencies
      run: dotnet restore "./HubService"
    - name: Build code
      run: dotnet build "./HubService" --configuration Release --no-restore
    - name: Publish application
      run: dotnet publish "./HubService" -c Release -o myApp    
        
